repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: npx standard --fix
        language: system
        pass_filenames: false
        verbose: true
        files: \.(js)$
